name: Ping API

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook
        run: curl -s https://api.360qm.co.th/Webhook/gmail_to_webhook.php
